Repository kalliope-project/kalliope, pull requests merged in 2018-04, with the labels that each got.

#429 [Refacto] Remove duplicate code for synapse launcher
  Tests/test_hook_manager.py
  Tests/test_init.py
  Tests/test_synapse_launcher.py
  kalliope/__init__.py
  kalliope/core/HookManager.py
  kalliope/core/ShellGui.py
  kalliope/core/SynapseLauncher.py
  kalliope/signals/event/event.py
  kalliope/signals/mqtt_subscriber/MqttClient.py
Labels: Refactor

#433 [Fix] Return default serialization when kalliope running
  kalliope/core/Lifo/LIFOBuffer.py
  kalliope/core/PlayerModule.py
  kalliope/core/RestAPI/FlaskAPI.py
Labels: bug

#436 Feature/introduce mute settings
  Docs/kalliope_cli.md
  Docs/rest_api.md
  Docs/settings.md
  Tests/settings/settings_test.yml
  Tests/test_hook_manager.py
  Tests/test_models.py
  Tests/test_settings_loader.py
  brain_examples/mute.yml
  kalliope/__init__.py
  kalliope/core/ConfigurationManager/SettingEditor.py
  kalliope/core/ConfigurationManager/SettingLoader.py
  kalliope/core/ConfigurationManager/__init__.py
  kalliope/core/HookManager.py
  kalliope/core/Lifo/LIFOBuffer.py
  kalliope/core/Models/Settings.py
  kalliope/core/NeuronModule.py
  kalliope/core/RestAPI/FlaskAPI.py
  kalliope/core/SynapseLauncher.py
  kalliope/neurons/deaf/README.md
  kalliope/neurons/deaf/__init__.py
  kalliope/neurons/deaf/deaf.py
  kalliope/neurons/neurotransmitter/neurotransmitter.py
  kalliope/neurons/neurotransmitter/tests/test_neurotransmitter.py
  kalliope/settings.yml
  kalliope/signals/order/order.py
Labels: bug, enhancement

#437 Doc enhancement
  Docs/brain.md
  Docs/contributing.md
  Docs/installation.md
  Docs/installation/quickstart.md
  Docs/installation/raspbian.md
  Docs/kalliope_cli.md
  Docs/neuron_list.md
  Docs/neurons.md
  Docs/player.md
  Docs/rest_api.md
  Docs/settings.md
  Docs/signals.md
  Docs/stt.md
  Docs/tts.md
Labels: Documentation, enhancement
